## Genrate k-cores feature

k-core is kind of graphical feature pointing out the relation between data and how "popular" a data is.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df_kscore = pd.read_csv('./question_kcores.csv')

In [3]:
df_train = pd.read_csv('../dataset/quora-question-pairs/train.csv')
df_test = pd.read_csv('../dataset/quora-question-pairs/test.csv')

df_train['question1'] = df_train['question1'].str.lower()
df_train['question2'] = df_train['question2'].str.lower()
df_test['question1'] = df_train['question1'].str.lower()
df_test['question2'] = df_train['question2'].str.lower()

In [4]:
d = {}

for i in range(len(df_kscore)):
    series = df_kscore.ix[i]
    d[series['question']] = series['kcores']
    if i%100000==0:
        print(i)

0
100000
200000
300000
400000

KeyboardInterrupt:

In [ ]:
SET = 'train'
# SET = 'test'

if SET=='train':
    df = df_train
else:
    df = df_test

out1 = []
out2 = []
for i,series in df.iterrows():
    
    q1 = d[ series['question1'] ]
    q2 = d[ series['question2'] ]
    
    out1.append(q1)
    out2.append(q2)
    
    if i%100000==0:
        print(i, '/', len(df))
    
df_res = pd.DataFrame(np.array([out1,out2]).reshape(-1,2), columns=['kscore1','kscore2'])
df_res.to_csv('./features_from_model/'+SET+'/k_scrore.csv', index=False)

In [13]:
SET = 'test'

f_name = './features_from_model/'+SET+'/k_scrore.csv'
df = pd.read_csv(f_name)
# del df['Unnamed: 0']
# df.to_csv(f_name, index = False)

In [14]:
df

         kscore1  kscore2
0              1        1
1              1        1
2              1        1
3              1        1
4              2        1
5              1        1
6              2        2
7              2        7
8              1        1
9             20        1
10             1        1
11             2        1
12             1        2
13             3        1
14            30        8
15             1        2
16             1        1
17             1        1
18             1        1
19             6        1
20             1        1
21             1        1
22             1        1
23             1        1
24             2        2
25             1        1
26             1        2
27             1        1
28             1        2
29             7        3
...          ...      ...
2345766        2        2
2345767        2        2
2345768        2        2
2345769        2        2
2345770        2        2
2345771        2        2
2345772        2        2
2345773        2        2
2345774        2        2
2345775        2        2
2345776        2        2
2345777        2        2
2345778        2        2
2345779        2        2
2345780        2        2
2345781        2        2
2345782        2        2
2345783        2        2
2345784        2        2
2345785        2        2
2345786        2        2
2345787        2        2
2345788        2        2
2345789        2        2
2345790        2        2
2345791        2        2
2345792        2        2
2345793        2        2
2345794        2        2
2345795        2        2

[2345796 rows x 2 columns]